package com.example.homehub.constants

object Constants {
    // MQTT
    const val MQTT_TOPIC_MAIN_GATE_OPEN = "gate-main/open"
    const val MQTT_TOPIC_MAIN_GATE_CLOSE = "gate-main/close"
    const val MQTT_TOPIC_MAIN_GATE_STATUS_GATE = "gate-main/status/gate"
    const val MQTT_TOPIC_MAIN_GATE_STATUS_OPERATION = "gate-main/status/operation"
    const val MQTT_TOPIC_MAIN_GATE_STATUS_SYSTEM = "gate-main/status/system"
    const val MQTT_TOPIC_MAIN_GATE_CONFIG = "gate-main/config"
    const val MQTT_TOPIC_MAIN_GATE_REBOOT = "gate-main/reboot"

    // Preferences
    const val PREFERENCES_STORE_NAME = "HomeHubPreferences"

    const val PREFERENCE_MQTT_HOST = "MQTT_HOST"
    const val PREFERENCE_MQTT_PORT = "MQTT_PORT"
    const val PREFERENCE_MQTT_USER = "MQTT_USER"
    const val PREFERENCE_MQTT_PASS = "MQTT_PASS"

    const val PREFERENCE_USER_ID = "USER_ID"

    const val PREFERENCE_MAIN_GATE_CONFIG_DELAYED_AUTOCLOSE_ENABLED =
        "MAIN_GATE_CONFIG_DELAYED_AUTOCLOSE_ENABLED"
    const val PREFERENCE_MAIN_GATE_CONFIG_UNOBSTRUCTED_AUTOCLOSE_ENABLED =
        "MAIN_GATE_CONFIG_UNOBSTRUCTED_AUTOCLOSE_ENABLED"
    const val PREFERENCE_MAIN_GATE_CONFIG_DELAYED_AUTOCLOSE_SECONDS =
        "PREFERENCE_MAIN_GATE_CONFIG_DELAYED_AUTOCLOSE_SECONDS"
    const val PREFERENCE_MAIN_GATE_CONFIG_UNOBSTRUCTED_AUTOCLOSE_SECONDS =
        "PREFERENCE_MAIN_GATE_CONFIG_UNOBSTRUCTED_AUTOCLOSE_SECONDS"

    const val PREFERENCE_MAIN_GATE_CONFIG_DELAYED_AUTOCLOSE_ENABLED_DEFAULT = false
    const val PREFERENCE_MAIN_GATE_CONFIG_UNOBSTRUCTED_AUTOCLOSE_ENABLED_DEFAULT = false
    const val PREFERENCE_MAIN_GATE_CONFIG_DELAYED_AUTOCLOSE_SECONDS_DEFAULT = 120
    const val PREFERENCE_MAIN_GATE_CONFIG_UNOBSTRUCTED_AUTOCLOSE_SECONDS_DEFAULT = 30

    // Logging
    const val LOG_TAG_MQTT = "MQTT"
    const val LOG_TAG_MAIN_GATE = "MainGate"
    const val LOG_FILE_NAME = "home_hub.log"
}